USE blis_revamp;

UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
INSERT INTO user(username, password, actualname, level, created_by, lab_config_id, email, phone, lang_id) VALUES ('kaneshie_tech1', '56cbdfb7197c476fdd872cf2872f38131d24c8be', '', 0, 338, 153, '', '', 'default');
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
UPDATE lab_config SET name='Kaneshie Polyclinic', location='Ghana', admin_user_id=338, id_mode=1 WHERE lab_config_id=153;
